# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './APITempoDIO/*.sln'
  buildPlatform: 'any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Instal .Net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: dotnet restore $(solution)
  displayName: 'Restore solution'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build solution'

- task: Docker@2
  inputs:
    containerRegistry: 'acrapidemomatsuora'
    repository: 'api-dio-teste'
    command: 'buildAndPush'
    Dockerfile: './APITempoDIO/APITempoDIO/Dockerfile'